### ISSUE TITLE
Pundit error after update

### ISSUE THREAD

**Issue by navvyua** [ergoserv/auxiliary_rails_resourceable#3]
`uninitialized constant Pundit::Authorization (NameError)`

Resolved after `pundit` update (Fetching pundit 2.3.1 (was 2.0.0)), maybe version should be specified in gemspec.

**Comment by stgeneral** [comment]
Indeed, it requires at least the '2.2.0` version: https://github.com/varvet/pundit/blob/main/CHANGELOG.md#220-2022-02-11. But [2.3.1](https://github.com/varvet/pundit/blob/main/CHANGELOG.md#231-2023-07-17) is even better.
@navvyua will you be able to prepare a pull request with the updates?
